export const data = [
  {
    id: 1,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "Yunusobod Toshkent",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "5,600",
    after: "9,500",
  },
  {
    id: 2,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "Villa of Alisher Usmanov",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 3500,
    before: "2,200",
    after: "7,500",
  },
  {
    id: 3,
    bgImg: "./images/3hous.png",
    personImg: "../images/person3.png",
    title: "New department office",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 6,
    bath: 3,
    garage: 2,
    field: 4200,
    before: "1,800",
    after: "7,500",
  },
  {
    id: 4,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "Webbrain Acadamy",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 4,
    field: 1200,
    before: "2,800",
    after: "8,500",
  },
  {
    id: 5,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
  {
    id: 6,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
  {
    id: 7,
    bgImg: "./images/3hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "Uzbekistan",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
  {
    id: 8,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
  {
    id: 9,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 1,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,500",
    after: "7,800",
  },
  {
    id: 10,
    bgImg: "./images/3hous.png",
    personImg: "../images/person1.png",
    title: "Tashkent University of Information",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
  {
    id: 11,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
  {
    id: 12,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: "2,800",
    after: "7,500",
  },
];
