export const data = [
  {
    id: 1,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "Yunusobod Toshkent",
    zip: "Beruniy St",
    city: "Shayxontohur",
    region: "Tashkent",
    country: "Uzbekistan",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 5600,
    isliked: false,
    after: 9500,
  },
  {
    id: 2,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "Villa of Alisher Usmanov",
    zip: "Amit Temur St",
    city: "Yunusobod",
    region: "Tashkent",
    country: "Uzbekistan",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 3500,
    before: 2200,
    isliked: false,
    after: 7500,
  },
  {
    id: 3,
    bgImg: "./images/3hous.png",
    personImg: "../images/person3.png",
    title: "New department office",
    zip: "Marg'iloniy St",
    city: "Margilan",
    region: "Fergana",
    country: "Uzbekistan",
    bed: 6,
    bath: 3,
    garage: 2,
    field: 4200,
    before: 1800,
    isliked: false,
    after: 7500,
  },
  {
    id: 4,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "Webbrain Acadamy",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "London",
    country: "Great Britan",
    bed: 4,
    bath: 3,
    garage: 4,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 8500,
  },
  {
    id: 5,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "New Apartment Nice Wiew",
    zip: "Names St",
    city: "Sidney",
    region: "Capital",
    country: "Australia",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
  {
    id: 6,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Lusies St",
    city: "Los-angelas",
    region: "Los-angelas",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
  {
    id: 7,
    bgImg: "./images/3hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "Uzbekistan",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
  {
    id: 8,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "Ostana",
    country: "Kazogistan",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
  {
    id: 9,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "Dubay",
    country: "Saudia-arabiya",
    bed: 1,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2500,
    isliked: false,
    after: 7800,
  },
  {
    id: 10,
    bgImg: "./images/3hous.png",
    personImg: "../images/person1.png",
    title: "Tashkent University of Information",
    zip: "Quincy St",
    city: "Brooklyn",
    region: "NY",
    country: "USA",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
  {
    id: 11,
    bgImg: "./images/2hous.png",
    personImg: "../images/person2.png",
    title: "New Apartment Nice Wiew",
    zip: "Pushkin St",
    city: "Moscva",
    region: "Kazan",
    country: "Russia",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
  {
    id: 12,
    bgImg: "./images/1hous.png",
    personImg: "../images/person1.png",
    title: "New Apartment Nice Wiew",
    zip: "Lyow St",
    city: "Berlin",
    region: "Paris",
    country: "Germany",
    bed: 4,
    bath: 3,
    garage: 2,
    field: 1200,
    before: 2800,
    isliked: false,
    after: 7500,
  },
];
